### ISSUE TITLE
Cascading behavior when creating a new tab in Iterm2 while plot is running.

### ISSUE THREAD

**Issue by matsch01** [rs/jplot#2]
If I start jplot and then create another tab in Iterm, the plot starts cascading. 

![jplot_issue](https://user-images.githubusercontent.com/1692616/36681503-cb0fd410-1ae6-11e8-9eda-cc0ef1a95b3b.jpeg)

Any idea what's causing this?

**Comment by rs** [comment]
If you restart jplot when this happen, does it continue?

**Comment by matsch01** [comment]
Yes

**Comment by rs** [comment]
Which version of iTerm do you have?

**Comment by matsch01** [comment]
Build 3.1.5

**Comment by rs** [comment]
Can you try 3.2.20180221-nightly?

**Comment by matsch01** [comment]
I tried Build 3.2.20180224-nightly. Same behavior.

**Comment by rs** [comment]
Can you send your "appearance" perference tab?

**Comment by matsch01** [comment]
![image](https://user-images.githubusercontent.com/1692616/36753274-adc93e8a-1bd3-11e8-860c-83aea41d6db3.png)

**Comment by rs** [comment]
Sorry I can't reproduce. If you have more info to share on how to reproduce, it would be helpful.

**Comment by matsch01** [comment]
I can reproduce as follows:

1. Start the following server:

```
package main

import (
	_ "expvar"
	"fmt"
	"log"
	"net/http"
)

func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hi there!")
}

func main() {
	http.HandleFunc("/", handler)
	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

2. Open iTerm and run the following:
`jplot --url http://:8080/debug/vars memstats.HeapAlloc+memstats.HeapSys+memstats.HeapAlloc`

3. Open new tab in iTerm (⌘T).
4. Go back to Tab 1 where jplot is running.
5. You must scroll up to see the cascading behavior.

**Comment by rs** [comment]
This should fix your issue. Please reopen if not.

**Comment by matsch01** [comment]
Perfect.
